# config based on splade++_max and splade_monogpu
defaults:
  ############## TRAIN ###################################
  - train/config: splade_monogpu
  - train/data: mmarco-pt-4M
  - train/model: splade_bertimbau
  ############## INDEX ###################################
  - index: mrobust-pt
  ############## RETRIEVE ################################
  - retrieve_evaluate: mrobust-pt
  ############### FLOPS ##################################
  - flops: mmarco-pt

config:
  checkpoint_dir: models/splade_mmarco_pt/checkpoint
  index_dir: models/splade_mrobust_pt/index
  out_dir: models/splade_mrobust_pt/out
