# config based on splade++_max and splade_monogpu
defaults:
  ############## TRAIN ###################################
  - train/config: splade_monogpu
  - train/data: mmarco-pt-100k
  - train/model: splade_bertimbau
  ############## INDEX ###################################
  - index: mmarco-pt
  ############## RETRIEVE ################################
  - retrieve_evaluate: mmarco-pt
  ############### FLOPS ##################################
  - flops: mmarco-pt

config:
  checkpoint_dir: models/splade_mmarco_pt_100k/checkpoint
  index_dir: models/splade_mmarco_pt_100k/index
  out_dir: models/splade_mmarco_pt_100k/out
